on:
  schedule:
    - cron: '0 9 * * *' # everyday at 9am
    - cron: '0 23 * * *' # everyday at 11pm

# Dev Mainnet tests
name: DEV Mainnet tests

jobs:
  regressiontest_dev_mainnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'release-candidate-0.59.0'

      - uses: actions/setup-node@v2.5.1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: '14'
        # Create screenshots directory
      - run: mkdir screenshots

      - uses: actions/cache@v2
        env:
          node-version: 14.1.0
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}

      # Create Dev Wallet for nightly tests
      - name: Set development manifest
        env:
          VUE_APP_TERRA_MAINNET_URL: ${{ secrets.VUE_APP_TERRA_MAINNET_URL }}
          VUE_APP_AVALANCHE_MAINNET_NODE: ${{ secrets.VUE_APP_AVALANCHE_MAINNET_NODE }}
          VUE_APP_AVALANCHE_TESTNET_NODE: ${{ secrets.VUE_APP_AVALANCHE_TESTNET_NODE }}
          VUE_APP_NEAR_MAINNET_URL: ${{ secrets.VUE_APP_NEAR_MAINNET_URL }}
        run: |
          echo VUE_APP_TERRA_MAINNET_URL =${{ secrets.VUE_APP_TERRA_MAINNET_URL }} >> .env
          echo VUE_APP_AVALANCHE_MAINNET_NODE =${{ secrets.VUE_APP_AVALANCHE_MAINNET_NODE }} >> .env
          echo VUE_APP_AVALANCHE_TESTNET_NODE =${{ secrets.VUE_APP_AVALANCHE_TESTNET_NODE }} >> .env
          echo VUE_APP_NEAR_MAINNET_URL =${{ secrets.VUE_APP_NEAR_MAINNET_URL }} >> .env
          jq --argjson icons "{\"16\": \"icons/dev/16x16.png\",\"48\": \"icons/dev/48x48.png\",\"128\": \"icons/dev/128x128.png\"}" '.icons = $icons | .browser_action.default_icon = $icons | .name = "Liquality Wallet - Dev"' ./src/manifest.json > ./src/manifest.tmp
          mv ./src/manifest.tmp ./src/manifest.json
          npm ci
          npm run lint
          npm run build

      - name: Regression tests against Mainnet
        uses: beemi/puppeteer-headful@v1.0.11
        env:
          CI: 'true'
          DISPLAY: :99
          SEED_WORDS: ${{ secrets.TEST_NET_SEED_WORDS }}
          TWENTY_FOUR_SEEDS: ${{ secrets.TWENTY_FOUR_SEEDS }}
        with:
          args: npm run test:mainnet:devagent # Run tests against dev mainnet

      - name: Save Screenshots
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: ignore



